# Generated by Django 3.2.11 on 2022-02-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question_bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('optionA', models.TextField()),
                ('optionB', models.TextField()),
                ('optionC', models.TextField()),
                ('optionD', models.TextField()),
                ('answer', models.CharField(max_length=5)),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.question_bank')),
            ],
        ),
    ]
