# Generated by Django 3.2.11 on 2022-03-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_rename_question_question_question_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='contest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=5)),
                ('content', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='question_bank',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='question_bank',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
    ]
