# Generated by Django 3.2.11 on 2022-03-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20220314_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='content',
        ),
        migrations.AddField(
            model_name='contest',
            name='config',
            field=models.CharField(default='  ', max_length=50),
        ),
        migrations.AddField(
            model_name='contest',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='type',
            field=models.CharField(choices=[('RA', 'random'), ('FI', 'fixed'), ('SE', 'select')], default='RA', max_length=2),
        ),
    ]
