# Generated by Django 3.2.11 on 2022-03-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20220322_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='name',
            field=models.CharField(default=' ', max_length=11),
        ),
        migrations.AlterField(
            model_name='contest',
            name='config',
            field=models.CharField(default='{}', max_length=50),
        ),
    ]
