# Generated by Django 3.2.11 on 2022-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20220322_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='duration',
            field=models.ImageField(blank=True, upload_to='', verbose_name='时长'),
        ),
        migrations.AddField(
            model_name='contest',
            name='starttime',
            field=models.DateField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('IN', 'waited'), ('RE', 'released'), ('CL', 'closed')], default='IN', max_length=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='config',
            field=models.CharField(blank=True, max_length=50, verbose_name='配置'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(default=' ', max_length=11, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='type',
            field=models.CharField(choices=[('RA', 'random'), ('FI', 'fixed'), ('SE', 'select')], default='RA', max_length=2, verbose_name='类型'),
        ),
    ]
