# Generated by Django 3.2.11 on 2022-03-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220325_1740'),
        ('contest', '0007_auto_20220325_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='config',
            field=models.TextField(blank=True, max_length=50, verbose_name='配置'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(verbose_name='分数')),
                ('details', models.TextField(verbose_name='')),
                ('contest', models.ManyToManyField(to='contest.Contest')),
                ('user', models.ManyToManyField(to='user.User')),
            ],
        ),
    ]
