# Generated by Django 3.2.11 on 2022-04-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20220329_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_bank',
            name='description',
            field=models.TextField(null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='contest',
            field=models.ManyToManyField(to='contest.Contest'),
        ),
    ]
