# Generated by Django 3.2.11 on 2022-04-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20220406_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='type',
        ),
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=11, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('IN', 'waited'), ('RE', 'released'), ('CL', 'closed')], default='RE', max_length=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='contest',
            field=models.ManyToManyField(to='contest.Contest'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SC', 'single choice'), ('MC', 'multiple choice'), ('JQ', 'judgement')], default='SC', max_length=2),
        ),
    ]
