# Generated by Django 3.2.11 on 2022-04-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220325_1740'),
        ('contest', '0014_auto_20220408_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='contest',
        ),
        migrations.AddField(
            model_name='grade',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='user',
        ),
        migrations.AddField(
            model_name='grade',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
