# Generated by Django 3.2.6 on 2021-09-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img_url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
