# Generated by Django 3.2.11 on 2022-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220322_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrators',
            name='group',
            field=models.ManyToManyField(to='user.Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(to='user.Group'),
        ),
    ]
